from enum import Enum


class AuditEvent(str, Enum):
    """
    All audit log events
    KDPA Article 28 compliance requires every patient data access to be logged
    """

    # Patient data
    PATIENT_VIEWED = "PATIENT_VIEWED"
    PATIENT_RECORD_ACCESSED = "PATIENT_RECORD_ACCESSED"
    PATIENT_CREATED = "PATIENT_CREATED"
    PATIENT_UPDATED = "PATIENT_UPDATED"
    PATIENT_ARCHIVED = "PATIENT_ARCHIVED"
    PATIENT_SEARCHED = "PATIENT_SEARCHED"

    # Clinical
    CONSULTATION_CREATED = "CONSULTATION_CREATED"
    CONSULTATION_SIGNED = "CONSULTATION_SIGNED"
    CONSULTATION_ADDENDUM = "CONSULTATION_ADDENDUM"
    PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED"
    PRESCRIPTION_DISPENSED = "PRESCRIPTION_DISPENSED"
    PRESCRIPTION_REJECTED = "PRESCRIPTION_REJECTED"
    VITALS_RECORDED = "VITALS_RECORDED"
    LAB_RESULT_RECORDED = "LAB_RESULT_RECORDED"
    IMAGING_RESULT_RECORDED = "IMAGING_RESULT_RECORDED"
    REFERRAL_CREATED = "REFERRAL_CREATED"

    # AI safety monitoring
    AI_TRIAGE_COMPLETED = "AI_TRIAGE_COMPLETED"
    AI_SUGGESTION_ACCEPTED = "AI_SUGGESTION_ACCEPTED"
    AI_SUGGESTION_MODIFIED = "AI_SUGGESTION_MODIFIED"
    AI_SUGGESTION_REJECTED = "AI_SUGGESTION_REJECTED"
    AI_CALL_FAILED = "AI_CALL_FAILED"
    AI_JOB_QUEUED = "AI_JOB_QUEUED"
    AI_JOB_COMPLETED = "AI_JOB_COMPLETED"

    # Authentication
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    OTP_SENT = "OTP_SENT"
    OTP_VERIFIED = "OTP_VERIFIED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"

    # Security
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RATE_LIMIT_HIT = "RATE_LIMIT_HIT"

    # KDPA governance
    CONSENT_GRANTED = "CONSENT_GRANTED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    DATA_EXPORT_REQUESTED = "DATA_EXPORT_REQUESTED"
    DATA_EXPORT_COMPLETED = "DATA_EXPORT_COMPLETED"
    DATA_ERASURE_REQUESTED = "DATA_ERASURE_REQUESTED"
    DATA_ERASURE_COMPLETED = "DATA_ERASURE_COMPLETED"

    # SHIF Claims (formerly NHIF - Social Health Insurance Fund rebranded to SHIF)
    SHIF_CLAIM_CREATED = "SHIF_CLAIM_CREATED"
    SHIF_CLAIM_SUBMITTED = "SHIF_CLAIM_SUBMITTED"
    SHIF_CLAIM_PAID = "SHIF_CLAIM_PAID"
    SHIF_CLAIM_REJECTED = "SHIF_CLAIM_REJECTED"
